-- 1.6 MISE À JOUR et suppression d’enregistrements
-- Supprimer l’hypermarché ‘Marrefour Market’.
DELETE FROM HYPERMARCHE WHERE NOM = 'Marrefour Market';

-- Descriptifs des rayons dont les chiffres d'affaires sont supérieurs à 1 000 000
SELECT DESCRIPTIF
FROM RAYON
WHERE CHIFFREAFFAIRE > 1000000;

SELECT NOM
FROM HYPERMARCHE
WHERE VILLE = 'Calais';

SELECT NOM
FROM HYPERMARCHE
WHERE CODEPOSTAL LIKE '62%';

SELECT EMPLOYE.NOM, EMPLOYE.PRENOM
FROM EMPLOYE
JOIN RAYON ON EMPLOYE.NUMERO = RAYON.NUMERORESPONSABLE
WHERE RAYON.CHIFFREAFFAIRE > 1000000;

SELECT EMPLOYE.NOM, EMPLOYE.PRENOM
FROM EMPLOYE
JOIN RAYON ON EMPLOYE.NUMERO = RAYON.NUMERORESPONSABLE
JOIN HYPERMARCHE ON RAYON.NUMEROHYPER = HYPERMARCHE.NUMERO
WHERE HYPERMARCHE.NOM = 'Marrefour Coquelles'
  AND RAYON.CHIFFREAFFAIRE < 500000;

SELECT HYPERMARCHE.NOM, EMPLOYE.NOM, EMPLOYE.PRENOM
FROM HYPERMARCHE
JOIN RAYON ON HYPERMARCHE.NUMERO = RAYON.NUMEROHYPER
JOIN EMPLOYE ON HYPERMARCHE.NUMERODIRECTEUR = EMPLOYE.NUMERO
WHERE HYPERMARCHE.VILLE = 'Calais'
  AND RAYON.CHIFFREAFFAIRE < 500000
  AND RAYON.NUMERORESPONSABLE = 'EMP4328';  -- Numéro de Max Stevenson

SELECT HYPERMARCHE.NOM
FROM HYPERMARCHE
JOIN RAYON ON HYPERMARCHE.NUMERO = RAYON.NUMEROHYPER
WHERE RAYON.CHIFFREAFFAIRE = (SELECT MAX(CHIFFREAFFAIRE) FROM RAYON);

SELECT HYPERMARCHE.NOM
FROM HYPERMARCHE
JOIN (
  SELECT NUMEROHYPER, RANK() OVER (ORDER BY CHIFFREAFFAIRE DESC) AS RANK
  FROM RAYON
) RANKED_RAYON ON HYPERMARCHE.NUMERO = RANKED_RAYON.NUMEROHYPER
WHERE RANKED_RAYON.RANK = 1;

SELECT EMPLOYE.NOM, EMPLOYE.PRENOM
FROM EMPLOYE
JOIN RAYON ON EMPLOYE.NUMERO = RAYON.NUMERORESPONSABLE
JOIN HYPERMARCHE ON RAYON.NUMEROHYPER = HYPERMARCHE.NUMERO
WHERE HYPERMARCHE.NOM = 'Marrefour Coquelles'
  AND RAYON.CHIFFREAFFAIRE = (SELECT MAX(CHIFFREAFFAIRE) 
                              FROM RAYON WHERE NUMEROHYPER = HYPERMARCHE.NUMERO);


SELECT HYPERMARCHE.NOM
FROM HYPERMARCHE
JOIN RAYON ON HYPERMARCHE.NUMERO = RAYON.NUMEROHYPER
WHERE RAYON.CHIFFREAFFAIRE != (SELECT MAX(CHIFFREAFFAIRE) FROM RAYON);

SELECT HYPERMARCHE.NOM, SUM(RAYON.CHIFFREAFFAIRE) AS CA_TOTAL
FROM HYPERMARCHE
JOIN RAYON ON HYPERMARCHE.NUMERO = RAYON.NUMEROHYPER
GROUP BY HYPERMARCHE.NOM;

SELECT SUM(RAYON.CHIFFREAFFAIRE) AS CA_TOTAL
FROM HYPERMARCHE
JOIN RAYON ON HYPERMARCHE.NUMERO = RAYON.NUMEROHYPER
JOIN EMPLOYE ON HYPERMARCHE.NUMERODIRECTEUR = EMPLOYE.NUMERO
WHERE EMPLOYE.NOM = 'Dupont' AND EMPLOYE.PRENOM = 'Jean'
  AND EXISTS (
    SELECT 1
    FROM RAYON R
    JOIN EMPLOYE E ON R.NUMERORESPONSABLE = E.NUMERO
    WHERE R.NUMEROHYPER = HYPERMARCHE.NUMERO
      AND E.NOM = 'Durand' AND E.PRENOM = 'Christophe'
  );


SELECT HYPERMARCHE.NOM, SUM(RAYON.CHIFFREAFFAIRE) AS CA_TOTAL
FROM HYPERMARCHE
JOIN RAYON ON HYPERMARCHE.NUMERO = RAYON.NUMEROHYPER
GROUP BY HYPERMARCHE.NOM
HAVING AVG(RAYON.CHIFFREAFFAIRE) > 1500000;


